#!/bin/bash

export PACKAGE_CORE_NAME="infra"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION=v0.21.0
export PACKAGE_CORE_ORG="infrahq"

# export PACKAGE_CORE_RELEASE_DOWNLOAD=${PACKAGE_CORE_RELEASE_DOWNLOAD:-"https://github.com/${PACKAGE_CORE_ORG}/infra/releases/download"}
export PACKAGE_CORE_RELEASE_DOWNLOAD="https://github.com/${PACKAGE_CORE_ORG}/infra/releases/download"
