#!/bin/bash

install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local os="$PACKAGE_OS"
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  case $arch in
  arm64) ;;

  amd64)
    arch="x86_64"
    ;;
  *)
    log::error "[$(timestamp)] unsupport arch: $arch"
    return 1
    ;;
  esac

  # files
  local tmp_file="$name.zip"
  local source_bin_file="./$name"
  # local target_bin_file="$usr_bin_dir/$name"

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/infrahq/infra/releases
  # example:
  #   https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_darwin_arm64.zip
  #   https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_darwin_x86_64.zip
  #   https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_linux_arm64.zip
  #   https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_linux_x86_64.zip
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/$PACKAGE_CORE_VERSION/${name}_${PACKAGE_CORE_VERSION#v}_${platform}_${arch}.zip"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  os::install $source_bin_file $usr_bin_dir $name

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
